name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ 'R2EShop.Domain', 'R2EShop.Contracts', 'R2EShop.Application', 'R2EShop.Infrastructure', 'R2EShop.API' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.202'

    - name: Restore dependencies
      run: dotnet restore ./R2EShop.API/${{ matrix.project }}/${{ matrix.project }}.csproj

    - name: Build
      run: dotnet build ./R2EShop.API/${{ matrix.project }}/${{ matrix.project }}.csproj --no-restore -c Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.project }}-build-artifacts
        path: |
          ./R2EShop.API/${{ matrix.project }}/bin/
          ./R2EShop.API/${{ matrix.project }}/obj/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.202'

    - name: Download R2EShop.Domain build artifacts
      uses: actions/download-artifact@v3
      with:
        name: R2EShop.Domain-build-artifacts
        path: .

    - name: Download R2EShop.Contracts build artifacts
      uses: actions/download-artifact@v3
      with:
        name: R2EShop.Contracts-build-artifacts
        path: .

    - name: Download R2EShop.Application build artifacts
      uses: actions/download-artifact@v3
      with:
        name: R2EShop.Application-build-artifacts
        path: .

    - name: Download R2EShop.Infrastructure build artifacts
      uses: actions/download-artifact@v3
      with:
        name: R2EShop.Infrastructure-build-artifacts
        path: .

    - name: Download R2EShop.API build artifacts
      uses: actions/download-artifact@v3
      with:
        name: R2EShop.API-build-artifacts
        path: .
          
    - name: Test
      run: dotnet test ./R2EShop.API/R2EShop.UnitTest/R2EShop.UnitTest.csproj --verbosity normal
