name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ 'R2EShop.Domain', 'R2EShop.Contracts', 'R2EShop.Application', 'R2EShop.Infrastructure', 'R2EShop.API' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.202'

    - name: Restore dependencies
      run: dotnet restore ./R2EShop.API/${{ matrix.project }}/${{ matrix.project }}.csproj

    - name: Build
      run: dotnet build ./R2EShop.API/${{ matrix.project }}/${{ matrix.project }}.csproj --no-restore -c Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.project }}-build-artifacts
        path: |
          ./R2EShop.API/${{ matrix.project }}/bin/
          ./R2EShop.API/${{ matrix.project }}/obj/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.202'

    - name: Download R2EShop.Domain build artifacts
      uses: actions/download-artifact@v3
      with:
        name: R2EShop.Domain-build-artifacts
        path: .

    - name: Download R2EShop.Contracts build artifacts
      uses: actions/download-artifact@v3
      with:
        name: R2EShop.Contracts-build-artifacts
        path: .

    - name: Download R2EShop.Application build artifacts
      uses: actions/download-artifact@v3
      with:
        name: R2EShop.Application-build-artifacts
        path: .

    - name: Download R2EShop.Infrastructure build artifacts
      uses: actions/download-artifact@v3
      with:
        name: R2EShop.Infrastructure-build-artifacts
        path: .

    - name: Download R2EShop.API build artifacts
      uses: actions/download-artifact@v3
      with:
        name: R2EShop.API-build-artifacts
        path: .
          
    - name: Test
      run: dotnet test ./R2EShop.API/R2EShop.UnitTest/R2EShop.UnitTest.csproj --verbosity normal

  push:
      runs-on: ubuntu-latest
      needs: test
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Build Docker image
        run: docker build -t build-env:latest -f ./R2EShop.API/R2EShop.API/Dockerfile ./R2EShop.API
        
      - name: Tag Docker image
        run: docker tag build-env:latest khoitranminh592003/r2eshop:latest
        
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
  
      - name: Push Docker image
        run: docker push khoitranminh592003/r2eshop:latest
        
  deploy:
    runs-on: ubuntu-latest
    needs: push    
    steps:
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
    - name: Activate Deploy Hook
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"build": true}' ${{ secrets.HOST_URL_HOOK_DEPLOY }}
